<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<?php init_head(); ?>
<div id="wrapper">
    <div class="content">
        <div class="row"><div class="col-md-5">
            <div class="panel_s"><div class="panel-body">
    <?php $this->load->view('payplex_commission/_statement_stamp', ['issue' => $issue]); ?>
                <div class="tw-flex tw-justify-between tw-items-center tw-mb-4">
                    <h4 class="no-margin"><?php echo html_escape($title); ?></h4>
                    <span class="label label-<?php echo Payplex_commission_workflow::stateClass($s['workflow_state']); ?>">
                        <?php echo html_escape($s['workflow_state']); ?></span>
                </div>
                <table class="table table-condensed">
                    <tbody>
                        <tr><td class="bold">Staff</td><td>#<?php echo (int) $s['staff_id']; ?></td></tr>
                        <tr><td class="bold">Period</td><td><?php echo html_escape($s['period']); ?></td></tr>
                        <tr><td class="bold">Gross earned</td><td><?php echo number_format((float) $s['gross_amount'], 2); ?></td></tr>
                        <tr><td class="bold">Clawed back</td><td class="text-danger"><?php echo number_format((float) $s['clawback_amount'], 2); ?></td></tr>
                        <tr><td class="bold">Net payable</td><td class="bold"><?php echo number_format((float) $s['net_amount'], 2); ?></td></tr>
                        <tr><td class="bold">Generated by</td><td>#<?php echo (int) $s['created_by']; ?></td></tr>
                        <tr><td class="bold">Approved by</td><td><?php echo $s['approved_by'] ? '#' . (int) $s['approved_by'] : '—'; ?></td></tr>
                    </tbody>
                </table>
                <?php if ($immutable): ?>
                    <div class="alert alert-warning no-mbot">
                        This statement is <strong><?php echo html_escape($s['workflow_state']); ?></strong> and can no
                        longer be edited. Gross earned stays as a historical fact; corrections are recorded
                        as adjustments below.
                    </div>
                <?php endif; ?>
            </div></div>

            <div class="panel_s"><div class="panel-body">
                <h5 class="bold no-mtop">Post an adjustment</h5>
                <p class="text-muted">Adjustments never modify the statement. They are recorded beside it.</p>
                <?php echo form_open(admin_url('payplex_commission/commission/add_adjustment')); ?>
                <input type="hidden" name="statement_id" value="<?php echo (int) $s['id']; ?>">
                <div class="form-group"><label>Type</label>
                    <select name="type" class="form-control">
                        <?php foreach ($adjTypes as $k => $label): ?>
                            <option value="<?php echo $k; ?>"><?php echo html_escape($label); ?></option>
                        <?php endforeach; ?>
                    </select></div>
                <div class="form-group"><label>Amount <small class="text-muted">(negative to recover)</small></label>
                    <input type="text" name="amount" class="form-control"></div>
                <div class="form-group"><label>Reason</label>
                    <input type="text" name="reason" class="form-control" maxlength="500"></div>
                <button type="submit" class="btn btn-primary btn-sm">Record adjustment</button>
                <?php echo form_close(); ?>
            </div></div>
        </div>

        <div class="col-md-7">
            <div class="panel_s"><div class="panel-body">
                <h5 class="bold no-mtop">Adjustments</h5>
                <?php if (!$adjustments): ?>
                    <p class="text-muted"><em>None.</em></p>
                <?php else: ?>
                <table class="table table-condensed table-striped">
                    <thead><tr><th>#</th><th>Type</th><th>Amount</th><th>Reason</th><th>By</th><th>When</th></tr></thead>
                    <tbody>
                    <?php foreach ($adjustments as $a): ?>
                        <tr>
                            <td><?php echo (int) $a['id']; ?></td>
                            <td><span class="label label-<?php echo (float) $a['amount'] < 0 ? 'danger' : 'success'; ?>">
                                <?php echo html_escape($a['type']); ?></span></td>
                            <td class="bold"><?php echo number_format((float) $a['amount'], 2); ?></td>
                            <td><small><?php echo html_escape($a['reason']); ?></small></td>
                            <td>#<?php echo (int) $a['created_by']; ?></td>
                            <td><small><?php echo html_escape($a['created_at']); ?></small></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <?php endif; ?>
            </div></div>

            <div class="panel_s"><div class="panel-body">
                <h5 class="bold no-mtop">Audit trail</h5>
                <table class="table table-condensed">
                    <tbody>
                    <?php if (!$audit): ?>
                        <tr><td class="text-muted"><em>No entries.</em></td></tr>
                    <?php else: foreach ($audit as $a): ?>
                        <tr><td>
                            <small class="text-muted"><?php echo html_escape($a->occurred_at); ?></small>
                            <span class="label label-default"><?php echo html_escape($a->action); ?></span>
                            <?php if ($a->from_state || $a->to_state): ?>
                                <small><?php echo html_escape($a->from_state ?: '—'); ?> &rarr;
                                <?php echo html_escape($a->to_state ?: '—'); ?></small>
                            <?php endif; ?>
                            by #<?php echo (int) $a->actor_id; ?>
                            <?php if ($a->reason): ?><br><small><?php echo html_escape($a->reason); ?></small><?php endif; ?>
                        </td></tr>
                    <?php endforeach; endif; ?>
                    </tbody>
                </table>
            </div></div>
        </div></div>
    </div>
</div>
<?php init_tail(); ?>
</body>
</html>
